on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to install helm
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - run: | 
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          snap list
        shell: bash
      - name: Setup Helm
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          version: "v"


          #Look into splitting up into multiple action files: One to download the .sh for helm (or anything) and one to execute it